name: Setup
description: Download and install 3rd party software.
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2.0.2
      with:
        bun-version-file: .bun-version

    - name: Install Dependencies
      shell: bash
      run: bun i --frozen-lockfile

    - name: Configure Git
      shell: bash
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
